### ISSUE TITLE
Acabar el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/dorcas-s3-evaluacion-intermedia-estherpato#1]
Veo que has continuado en una rama, te dejo algunas pistas para que puedas mejorarlo ;)

- La carpeta components viene muy bien para organizar los archivos, pero no debes dejar fuera App.js, también es un componente.

- Eliminar registerServiceWorker.js, y sus referencias en index.js (ya que no lo usas).

- Añadir keys en los listados (https://reactjs.org/docs/lists-and-keys.html).

- Instalar la librería `prop-types` y añadir  comprobación de typos.

- Darle un poco de cariño al HTML.

También te recomiendo publicar en Github Pages para practicar ;)

A por ello!

**Comment by estherpato** [comment]
@nasivuela 
Nasi, no tengo muy claro lo de los typos.
Y para publicar en Github Pages seguí los pasos de la docu de clase y la docu de github y no he sido capaz...(o al menos ahora mismo dice que 'not found')

**Comment by estherpato** [comment]
Vale, lo de Github pages está resuelto

**Comment by nasivuela** [comment]
@estherpato ¿a que te refieres con los de los typos? Yo veo tus proptypes bien, igual un pelín escasos (podrían estar en todos los componentes ;)

**Comment by estherpato** [comment]
@nasivuela he añadido las proptypes en todos los componentes! Creo que ya estaría todo

**Comment by nasivuela** [comment]
Buen trabajo!!!
